Django/Django_Old/disa-py/disa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import urls_main

'''from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.autodiscover()'''

urlpatterns = [

    url(r'^py-disa/', include(urls_main)),

]

# admin.site.site_header = 'DISA'

# Keep this at the end only
# This is only for dev environment where gunicorn server is running
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Django_Old/disa-py/organisation/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

Django/Django_Old/disa-py/member/forms.py
from django.utils.html import escapejs, format_html
from django.forms.widgets import RadioSelect
from django import forms
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from django.db import connection


relativetype_choices=( ('friend','Friend'),
                       ('wife','Wife'),
                       ('husband','Husband'),
                       ('father','Father'),
                       ('mother','Mother'),
                       ('sister','Sister'),
                       ('brother','Brother'),
                       ('son','Son'), 
                       ('daughter','Daughter'),
                       ('Cousin','Cousin'),
                       ('inlaws','Inlaws'),
                       ('wellwisher','Wellwisher'),
                       ('guru','Guru')
                     )


gender_options = ( ('m','Male'),
                   ('f','Female'),
                   ('d','Data Not Available')
                 )

calendar_options = ( ('lunar','Lunar'),
                     ('solar','Solar'),
                     ('default','Default')
                   )
martialstatus_options =( ('single','Single'),
                         ('married','Married'),
                       )

current_options = (('excellent', 'Excellent'),
                       ('good', 'Good'),
                       ('poor', 'Poor'),
                       ('urgentrepair', 'UrgentRepair'),
                       ('abandon', 'Abandon'),
                      )

states = (('Andhra Pradesh', 'Andhra Pradesh'),
          ('Arunachal Pradesh', 'Arunachal Pradesh'),
          ('Assam', 'Assam'),
          ('Bihar', 'Bihar'),
          ('Chhatisgarh', 'Chhattisgarh'),
          ('Goa', 'Goa'),
          ('Gujarat', 'Gujarat'),
          ('Haryana', 'Haryana'),
          ('Himachal Pradesh', 'Himachal Pradesh'),
          ('Jammu & Kashmir', 'Jammu & Kashmir'),
          ('Jharkhand', 'Jharkhand'),
          ('Karnataka', 'Karnataka'),
          ('Kerala', 'Kerala'),
          ('Madhya Pradesh', 'Madhya Pradesh'),
          ('Maharashtra', 'Maharashtra'),
          ('Manipur', 'Manipur'),
          ('Meghalaya', 'Meghalaya'),
          ('Mizoram', 'Mizoram'),
          ('Nagaland', 'Nagaland'),
          ('Odisa', 'Odisha (Orissa)'),
          ('Punjab', 'Punjab'),
          ('Rajasthan', 'Rajasthan'),
          ('Sikkim', 'Sikkim'),
          ('Tamil Nadu', 'Tamil Nadu'),
          ('Telangana', 'Telangana'),
          ('Tripura', 'Tripura'),
          ('Uttar Pradesh', 'Uttar Pradesh'),
          ('Uttarakhand', 'Uttarakhand'),
          ('West Bengal', 'West Bengal'),
         )

Land_Type = (('gift', 'Gift'),
             ('sale', 'Sale'),
             ('lease', 'Lease'),
             ('will', 'Will'),
             ('exchange', 'Exchange'),
             ('license', 'Licenses'),
             ('allotment', 'Allotment'),
            )

slt_type = (('smt', 'Smt'),
            ('sri', 'Sri'),
            ('kumari', 'Kumari'),
            ('messers', 'Messers'),
           )

relation_type = (('son', 'Son'),
                 ('daughter', 'Daughter'),
                 ('wife', 'Wife'),
                )

originals = (('adp', 'ADP'),
              ('gbs', 'GBS'),
              ('vendor', 'Vendor/ Donor'),
             )

usage = (('agriculture', 'Agriculture'),
         ('ashrama', 'Ashrama'),
         ('commercial', 'Commercial'),
         ('residential', 'Residential'),
         ('redundant', 'Redundant'),
         ('disputed', 'Disputed'),
        )

management = (('self', 'Self'),
              ('trust', 'Affiliated_Trust'),
              ('person', 'Affiliated_Person'),
             )

instrument = (('license', 'License'),
              ('lease', 'Lease'),
              ('informal', 'Informal'),
             )

status = (('dispute', 'Dispute'),
          ('disposal', 'Disposal'),
          ('aquisition', 'Acquisition'),
         )

class HorizRadioRenderer(forms.RadioSelect.renderer):
    """ this overrides widget method to put radio buttons horizontally
        instead of vertically.
    """
    def render(self):
            """Outputs radios"""
            return mark_safe(u'\n'.join([u'%s\n' % w for w in self]))

class MemberForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(MemberForm,self).__init__(*args,**kwargs)
          self.fields['gender'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=gender_options)
          self.fields['gender'].value='d'
          self.fields['calendar_type'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=calendar_options)
          self.fields['calendar_type'].value='default'

          self.fields['maasam'].empty_label = "--Select Maasam--"
          self.fields['paksham'].empty_label = "--Select Paksham--"
          self.fields['tithi'].empty_label = "--Select Tithi--"
          self.fields['rasi'].empty_label = "--Select Raasi--"
          self.fields['nakshatram'].empty_label = "--Select Nakshatram--"


class SevaForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(SevaForm,self).__init__(*args,**kwargs)
          self.fields['calendar_type'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=calendar_options)
          self.fields['calendar_type'].value='default'

          self.fields['maasam'].empty_label = "--Select Maasam--"
          self.fields['paksham'].empty_label = "--Select Paksham--"
          self.fields['tithi'].empty_label = "--Select Tithi--"
          self.fields['raasi'].empty_label = "--Select Raasi--"
          self.fields['nakshatram'].empty_label = "--Select Nakshatram--"

class AssetLandForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(AssetLandForm,self).__init__(*args,**kwargs)
          self.fields['address'].widget.attrs['cols']= 10
          self.fields['address'].widget.attrs['rows'] = 5
          self.fields['specialinfoindetails'].widget.attrs['cols']= 10
          self.fields['specialinfoindetails'].widget.attrs['rows'] = 5

class AssetBuildingForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(AssetBuildingForm,self).__init__(*args,**kwargs)
          self.fields['currentstate'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=current_options)

class AssetEquipmentForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(AssetEquipmentForm,self).__init__(*args,**kwargs)
          self.fields['currentstate'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=current_options)

class TrusteeForm(forms.ModelForm):
     def __init__(self,*args,**kwargs):
          super(TrusteeForm,self).__init__(*args,**kwargs)
          self.fields['tenure_active'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=(('yes', 'Yes'),('no','No'),))
          self.fields['valid'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=(('yes','Yes'),('no', 'No'),))
          self.fields['active'].widget = RadioSelect(renderer=HorizRadioRenderer, choices=(('yes','Yes'),('no', 'No'),))


select_mode = ( ('all','All'),
                ('group','Group'),
                ('others','Others')
              )
select_month = ( ('01', 'January'),
                 ('02', 'February'),
                 ('03', 'March'),
                 ('04', 'April'),
                 ('05', 'May'),
                 ('06', 'June'),
                 ('07', 'July'),
                 ('08', 'August'),
                 ('09', 'September'),
                 ('10', 'October'),
                 ('11', 'November'),
                 ('12', 'December')
               )

class EmailForm(forms.Form):

    cur = connection.cursor()
    group_choices =  []
    group_list = []


    mode = forms.TypedChoiceField(choices=select_mode, widget=forms.RadioSelect(renderer=HorizRadioRenderer), initial = 'others')
    query = "Select name from sevaCategories;"
    cur.execute(query)
    group_choices = cur.fetchall()

    for each in group_choices:
        tmp = (each[0], each[0])
        group_list.append(tmp)

    cur.close()

    groups = forms.TypedChoiceField(choices=tuple(group_list), required=False)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def __init__(self, *args, **kwargs):
        super(EmailForm, self).__init__(*args, **kwargs)
        grouplist = []
        cur = connection.cursor()
        query = "select name from groupNames;"
        cur.execute(query)
        groupchoices = cur.fetchall()
        cur.close()
        for each in groupchoices:
           tmp = (each[0], each[0])
           grouplist.append(tmp)
        # Add select option to the typedchoice field
        self.fields['groups'].choices =[("","--Select Group--")] + grouplist + list(self.fields['groups'].choices)[1:]


class SmsForm(forms.Form):

    cur = connection.cursor()
    group_choices = []
    group_list = []

    mode = forms.TypedChoiceField(choices=select_mode, widget=forms.RadioSelect(renderer=HorizRadioRenderer), initial = 'others')
    query = "Select name from sevaCategories;"
    cur.execute(query)
    group_choices = cur.fetchall()
    cur.close()

    for each in group_choices:
        tmp = (each[0],each[0])
        group_list.append(tmp)

    groups = forms.TypedChoiceField(choices=tuple(group_list), required=False)

    message = forms.CharField(widget=forms.Textarea(attrs={'id':'template_msg_preview','class':'data-promotional'}), required=True)

    def __init__(self, *args, **kwargs):
        super(SmsForm, self).__init__(*args, **kwargs)
        cur = connection.cursor()
        grouplist = []
        query = "select name from groupNames;"
        cur.execute(query)
        groupchoices = cur.fetchall()
        cur.close()

        for each in groupchoices:
           tmp = (each[0], each[0])
           grouplist.append(tmp)
        self.fields['groups'].choices=[("","--Select Group--")] + grouplist + list(self.fields['groups'].choices)[1:]

Django/Django_Old/disa-py/organisation/forms.py
from django import forms

# place form definition here

Django/Django_Old/disa-py/organisation/views.py
# Create your views here.

Django/Django_Old/disa-py/templates/AdvancePuja.html
<html>
<body>

<p>Dear <b>{{member_slt}} {{member_name}}</b>, <br />
Jaya Guru Datta<br /><br />
Your {{seva_name}} will be performed at Datta Peetham on <b>{{seva_date}}</b>.<br />
You are welcome to attend. <br /><br />
With Best Regards,<br />
In Sadguru Seva<br />
Service Team, SGS Ashrama<br />
Avadhoota Datta Peetham</p>

</body>
</html>

Django/Django_Old/disa-py/templates/AnnualReminder.html
<html>
<body>

<p>Dear <b>{{member_slt}} {{member_name}}</b>,<br />
Jaya Guru Datta<br /><br />
Please update your contact details with <a href="adp@sgsdatta.org">adp@sgsdatta.org</a> to receive Prasadam and updatesfrom Datta Peetham regularly.<br /><br/>
With Best Regards,<br />
In Sadguru Seva<br />
Service Team, SGS Ashrama<br />
Avadhoota Datta Peetham</p>
</body>
</html>

Django/Django_Old/disa-py/templates/SevadayChange.html
<html>
<body>

<p>Dear <b> {{member_slt}} {{member_name}}</b>,<br />
Jaya Guru Datta<br /><br />
SSID <b>{{seva_ssid}}</b> is successfully updated in the ADP Register.<br />
If you have not requested, contact <a href="adp@sgsdatta.org">adp@sgsdatta.org</a> immediately.<br /><br />
With Best Regards,<br />
In Sadguru Seva<br />
Service Team, SGS Ashrama<br />
Avadhoota Datta Peetham</p>

</body>
</html>

Django/Django_Old/disa-py/templates/add_relationship.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}DISA{% endblock %}
{% block body_header %}{% include 'admin/header.html'%}{% endblock body_header %}
{% block stylesheets %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}
{% block body %}
<div class="container">
    <div class="content">
        <div class="page-header">
            <h1>Add Relationship</h1>
        </div>
        <div class="section">
        <div class="form-inline center">
         <form method="post"> 
           {% csrf_token %}
            <select id="relationship" name="relationship">
                <option>---Select Relative Type---</option>
                    <option value="mother">Mother </option>
                    <option value="father">Father </option>
                    <option value="children">Friend </option>
                    <option value="introducer">sister </option>
                    <option value="wife">wife </option>
                    <option value="husband">Husband </option>
                    <option value="son">son </option>
                    <option value="daughter">Daughter </option>
                    <option value="brother">Brother </option>
                    <option value="cousin">Cousin </option>
                    <option value="inlaws">Inlaws </option>
                    <option value="wellwisher">wellwisher </option>
                    <option value="guru">Guru </option> 
            </select>

            <button class="btn btn-success" name="submit" type="submit" id="get_href" style="margin-left:5px;">Submit</button>
            <div>


                    <div style="margin-bottom: 10px;">
                        <label class="radio-inline">
                            <input type="radio" name="searchBy" value="mid" checked="checked">Member Id</label>
                        <label class="radio-inline">
                            <input type="radio" name="searchBy" value="surname">Surname</label>
                     </div>
                     <div role="form" class="form-inline row hidden" id="searchBar">
                        <div class="form-group col-md-6" style="float: none;">
                            <div class="row">
                                <input name="search" type="text" class="form-control" id="member-search-common"
                                       style="width:35%;" placeholder="Surname"
                                       autofocus="autofocus">
                            </div>
                        </div>
                     </div>
                     <div class="btn-search-wrapper">
                            <button class="btn btn-sm btn-primary btn-search">
                                <span class="glyphicon glyphicon-search txt-search"></span> Search
                            </button>
                     </div>
                </div>
              </form>
           </div>
        </div>
                <div class="section search-results box-border-top" id="SearchData"></div>
 
  </div>
</div>
{% endblock %}
{% block body_footer %}{% include 'admin/footer.html'%}{% endblock body_footer %}
{% block javascripts %}
<script type="text/javascript">
$(document).on("click", "input[name='searchBy']", function(){
       var searchBy = $(this).val();
        // Providing search options based on the search type
        if (searchBy == 'mid') {
            if ($('#searchBar').hasClass('hidden')) {
                $('#searchBar').removeClass('hidden');
            }
            // To change place holder
            $('[name="search"]').attr("placeholder", "Member Id e.g. MID#001, MID#101");
        } 
        else {
            if (!$('#searchBar').hasClass('hidden')) {
                $('#searchBar').addClass('hidden');
            }
            $('[name="search"]').attr("placeholder", "Surname");

        }
    $("input[type='text']").val("");
}).on("input", "[type='text']",function(){
    var searchBy = $('input[name="searchBy"]:checked').val();
    var data = {};
    if (searchBy == "surname") {
        data["surname"] = $('input[name="search"]').val();
    } else if (searchBy == "mid") {
        searchKey = $.trim($('input[name="search"]').val());
        data["mid"] = searchKey.replace(/^\D+/g, "");
    }
    $(".btn-search-wrapper").addClass("searching");
    $.ajax({
        url: "{% url 'relationship-search' %}?q=" + searchBy,
        data:data,
        dataType: "html",
        success: function(result) {
            //var table = memberSearchResult(result);
            $(".btn-search-wrapper").removeClass("searching");
            $("#SearchData").html(result);
        },
        error: function() {}
    });
});
</script>
{% endblock javascripts %}

Django/Django_Old/disa-py/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    {% block head %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="{% block description %}{% endblock %}">
        {% block bootstrap %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <style> @media (min-width: 980px) { body { padding-top: 40px; } }</style>
        {% endblock %}
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'css/common.css' %}">
        {% block stylesheets %}{% endblock %}
        {% block favicon %}
            {% load static from staticfiles %}
            <link rel="icon" type="image/png" href='{% static "img/favicon.ico" %}'/>
        {% endblock %}
    {% endblock %}
</head>
<body>
{% block body_header %}{% endblock %}
{% block body %}{% endblock %}
{% block body_footer %}{% endblock %}
    <script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
{% block javascripts %}{% endblock %}
</body>
</html>

Django/Django_Old/disa-py/templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}DISA{% endblock %}
{% block body_header %}{% include 'admin/header.html'%}{% endblock body_header %}
{% block body %}
<div class="container">
    <div class="content">
        <div>
            <div class="page-header">
                <h2>
                    <span class="header">Seva Kartas </span>
                    <span class="pull-right">
                        <div class="form-inline hide">
                            <input type="text" class="input-small selectSevaDate hasDatepicker" name="to-date-input"
                                   placeholder="Seva Date" id="dp1458374067266">
                            <input type="hidden" class="input-small" name="sevaDate" value="2016-03-19">
                            <button type="submit" class="btn btn-primary">Go</button>
                        </div>
                    </span>
                </h2>
            </div>
            <div>
                <ul id="myTab" class="nav nav-tabs">
                    <li class="active"><a data-categoryid="all" data-toggle="tab">All Sevas</a></li>
                    <li class=""><a data-toggle="tab">Shashwata Seva</a></li>
                </ul>
                <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="Shashwata-Seva">
                        <div class="dashboard-content">
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th colspan="2" style="text-align:center">Donor</th>
                                    <th>Place</th>
                                    <th>Nakshatram</th>
                                    <th>Gotram</th>
                                </tr>
                                </thead>
                                <tbody class="dashboard-seva-collection">
                                {%for seva in seva_list%}
                                <tr class="dashboard-seva-tile">
                                    <td width="80px">
                                        <div>
                                            <img src="{% if seva.mid.photo %}{{seva.mid.photo}}{%else%}{% static 'img/user.jpg' %} {%endif%}" width="100px" height="100px"
                                                 alt="image" class="member-details-view details"
                                                 title="See member details.">
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            <span>MID#{{seva.mid.mid}}</span>
                                            <span style="margin-left: 10px;">{{seva.ssid}}</span>
                                        </div>
                                        <div>
                                            <span class="muted" style="font-size: smaller;">
                                                <i class="fa fa-user fa-fw"></i> InTheNameOf:
                                            </span>
                                            {{seva.mid.salutation}} {{seva.mid.name}}{{seva.mid.surname}}
                                        </div>
                                        <div style="position:relative;">
                                            <span class="muted" title="Donor">
                                            <i class="fa fa-fw fa-rupee" style="margin-right: 9px;"></i>
                                            <i  class="fa fa-user fa-fw"
                                               style="font-size: 10px;position: absolute;color: gray;left: 7px;top: 7px;"></i>
                                                <span style="font-size: smaller;">Donor:</span>
                                                {{seva.mid.salutation}} {{seva.mid.name}} {{seva.mid.surname}}
                                            </span>
                                        </div>

                                    </td>
                                    <td>
                                        <div title="Place">
                                            <i class="icon-map-marker" style="margin-right:13px;"></i>
                                            {{seva.mid.place}}
                                        </div>
                                    </td>
                                    <td>
                                        <div>
                                            <div style="text-transform:capitalize;">
                                            <span title="Nakshatram" class="muted">
                                                {% if seva.mid.nakshatram or seva.nakshatram%}
                                                <i class="icon-star"></i>
                                                {% if seva.mid.nakshatram %}{{seva.mid.nakshatram}}{% elif seva.nakshatram %}{{seva.nakshatram}}{%endif%}
                                                {%endif%}
                                            </span>
                                        </div>
                                    </td>
                                    <td>
                                        <div style="text-transform:capitalize;">
                                            <span title="Gotram" class="muted">
                                                {% if seva.mid.gotram%}
                                                <i class="fa fa-fw fa-anchor"></i>
                                                {{seva.mid.gotram}}
                                                {%endif%}
                                            </span>
                                        </div>
                                    </td>

                                </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                          </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}
{% block body_footer %}{% include 'admin/footer.html'%}{% endblock body_footer %}

Django/Django_Old/disa-py/templates/sms_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Send Sms{% endblock %}
{% block body_header %}{% include 'admin/header1.html'%}{% endblock body_header %}

{% block bootstrap %}
<link rel="stylesheet" href="{% static 'css/bootstrap3.css' %}">
{% endblock %}
{% block body %}
    <div class="container">
        <div class="content">
            <h1>Send SMS</h1>
            <form action="" method="post" id="id_sms">
                {% csrf_token %}
                <tr><th><label for="id_mode">Mode:</label></th>
                   <td>{{form.mode}}</td></tr><br/>
                <div id="mobile">
                    <tr><th><label for="to_number">Enter Mobile Number:</label></th>
                        <td><input class="form-control" type="text" name="number_list" placeholder="Enter comma separated 10 digit mobile numbers" id="to_number" multiple /></td></tr>
                </div>
                <div id="all_numbers">
                    <tr><th><label for="id_number">All Mobile Number:</label></th>
                        <td><input class="form-control" type="email" name="number_list" id="numbers_all" multiple readonly/></td></tr>
                </div>
                <div id="group_numbers">
                    <tr><th><label for="id_number">Group Mobile Number:</label></th></tr>
                    <tr><td><input class="form-control"  multiple readonly/></td></tr>
                    <tr><th><label for="id_groups">Groups:</label></th>
                        <td>{{form.groups}}</td></tr>
                </div>
                <tr><th><label for="template_msg_preview">Message:</label></th>
                    <td>{{form.message}}</td></tr>

                <div id="template_msg_preview_count"></div>
                <br /><br /><br />
                <div style="text-align:center">
                    <button  class="default btn btn-primary" onClick="return(Validate());">Send</button>
					<button class="btn btn-default" type="reset" name="reset">Reset</button>
               </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block body_footer %}{% include 'admin/footer.html'%}{% endblock body_footer %}
{% block javascripts %}
<script type="text/javascript">

$(function() {
    $('#to_number').focus();

    if($('form input[type=radio]:checked').val() == "others") {
         $('#mobile').show();
         $('#all_numbers').hide(); 
         $('#group_numbers').hide();
    }

    $('input:radio[value="others"]').click(function() {  
         if($(this).is(":checked")) {
             $('#mobile').show();
             $('#all_numbers').hide();
             $('#group_numbers').hide();
         }
    });

   
    $('input:radio[value="group"]').click(function() {
        if($(this).is(":checked")) { 
            $('#group_numbers').show();
            $('#mobile').hide()
            $('#all_numbers').hide();
                      
        }
    });
 
     $('input:radio[value="all"]').click(function() {
        if($(this).is(":checked")) {
            $('#all_numbers').show();
            $('#mobile').hide();
            $('#group_numbers').hide();
          
        }
    });

});

function displayVal() {
    var group_vl = $('#id_groups option:selected').text();
     $("#group_numbers input").val(group_vl);
     $("#all_numbers input").val("All")
}
$("select").change(displayVal);
displayVal();


$(document).on('keyup', '.data-promotional', function() {
    var smstext = $('#template_msg_preview').val();
    var input_chars=smstext.length;
    var char_per_sms=153;
     
    if(isDoubleByte(smstext)) {
        char_per_sms=63;
    }
    
    var total_sms=Math.ceil(input_chars/char_per_sms);
    var sms_remainder=input_chars%char_per_sms;
    
    if(sms_remainder<8 && sms_remainder>0 && total_sms>1) {
        total_sms--;
    }
    $('#template_msg_preview_count').html( "<p class='text-info'> Approx., Total characters: <strong>" + smstext.length + "</strong> Total SMS: <strong>" + total_sms + "</strong> <span class='glyphicon glyphicon-question-sign' id='limit_help' data-container='body' data-toggle='popover' data-trigger='hover' data-placement='bottom' data-content='Length of the SMS: Single message size constitutes maximum up to 160 characters in case of both GSM & CDMA including the header and footer  which is submitted to SMSC. In case the message is larger than the aforementioned characters, single message shall mean 153 characters for both GSM and CDMA. Please be aware that a single Unicode SMS can only contain a maximum of 70 characters. If a Unicode message is concatenated, it reduces the number of characters contained in each message part by 7.' style='cursor:pointer;'></span>");
                $('#limit_help').popover();
});

function isDoubleByte(str) {
    for (var i = 0, n = str.length; i < n; i++) {
        if (str.charCodeAt( i ) > 255) { return true; }
    }
    return false;
}


function Validate() {
    
    var regex = new RegExp("^[0-9,]+$");
    var mode = $('input[name="mode"]:checked').val();
    var mobile_input = $('#to_number').val();
    var numList = mobile_input.split(",");
    var isValid = regex.test(mobile_input);
    var msg = $('#template_msg_preview').val();

    if(msg == "") {
        alert("Please enter message.");
        return false;
    }
    //alert user if any field is empty/incorrect number in others mode
    if(mode == 'others' && mobile_input == "") {
        alert("Please Enter Mobile Number.");
        return false;
    }
    if(mode == 'others' && !isValid) {
        alert("Only numbers and (comma ',') is allowed.");
        return false;
    }
    for(num=0;num<=numList.length;num++) {
        var len = numList[num].length;
        
        if(mode == 'others' && len != 10) {
            alert("Please check number " + numList[num] + ". Number should be of 10 digits");
            return false;
        }
    }    
   
    $('#id_sms').submit();
    return true;
}   
</script>
{% endblock javascripts %}