Django/Django_Old/website3/music/urls.py
from django.conf.urls import url, include
from . import views

app_name ='music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name="index"),

    #/music/album_id/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    #/music/album_id/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite')
]

Django/Django_Old/website3/website3/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'music/', include('music.urls')),
]

Django/Django_Old/website3/music/models.py
from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    #title = models.IntegerField(max_length=100)
    def __str__(self):
        return self.artist + "-" + self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete= models.CASCADE)
    file_type = models.CharField(max_length=100)
    song_title = models.CharField(max_length=200)
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title

Django/Django_Old/website3/music/views.py
from .models import Album, Song
from django.shortcuts import render,get_object_or_404

def index(request):
    all_albums = Album.objects.all()
    return render(request,'music/index.html',{'all_albums':all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request,'music/detail.html',{'album':album})

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk = request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request,'music/detail.html',{'album':album, 'error_message':'You did not select any valid song',})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

Django/Django_Old/website3/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{% block title %}Home{% endblock %}</title>

<!-- Loads the path to your static files -->
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<link rel="stylesheet" type = "text/css" href = "{% static 'music/style.css' %}"/>

</head>
<body>

<nav class="navbar navbar-inverse" >
<div class="container-fluid">

<!--header-->
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="{% url 'music:index' %}">Home</a>
</div>

<!--items-->
<div class="collapse navbar-collapse" id="topNavBar">
<ul class="nav navbar-nav">
<li class="active">
<a href="{% url 'music:index' %}">
<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Album
</a>
</li>
<li class="">
<a href="#">
<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
</a>
</li>
</ul>
<form class="navbar-form navbar-left" role="search" method="get" action="#">
<div class="form-group">
<input type="text" class="form-control" name="q" value="">
</div>
<button type="submit" class="btn btn-default">Search</button>
</form>
<ul class="nav navbar-nav navbar-right">
<li class="">
<a href="#">
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
</a>
</li>
<li class="">
<a href="#">
<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
</a>
</li>
</ul>
</div>
</div>
</nav>
{% block body %}  <!--you can give any names in tha place of body and block-->
{% endblock %}

</body>
</html>

Django/Django_Old/website3/music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{% block body %}
<img src=" {{album.album_logo}}">
<h1> {{ album.artist }} </h1>
<h2> {{ album.album_title }} </h2>

{% if error_message %}
<p> <strong> {{error_message}} </strong> </p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
{% csrf_token %}
{% for song in album.song_set.all %}
<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
<label for="song{{ forloop.counter }}">
{{ song.song_title }}
{% if song.is_favorite %}
<img src="http://i.imgur.com/b9b13Rd.png" />
{% endif %}
</label><br>
{% endfor %}
<input type="submit" value="Favorite">
</form>
{% endblock %}

Django/Django_Old/website3/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
{% if all_albums %}
<h3> Music albums </h3>
<ul>
{% for album in all_albums %}
<li><a href=" {% url 'music:detail' album.id %} ">{{album.album_title}}</a> </li>
{% endfor %}
</ul>

{% else %}
<h3> You dont have any Albums </h3>
{% endif %}
{% endblock %}